-- MySQL Script generated by MySQL Workbench
-- Tue Jan  8 17:19:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema questionnaire
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema questionnaire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `questionnaire` DEFAULT CHARACTER SET utf8 ;
USE `questionnaire` ;

-- -----------------------------------------------------
-- Table `questionnaire`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire`.`user` ;

CREATE TABLE IF NOT EXISTS `questionnaire`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `sex` VARCHAR(45) NULL,
  `age` INT NULL,
  `experience` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionnaire`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire`.`image` ;

CREATE TABLE IF NOT EXISTS `questionnaire`.`image` (
  `image_id` INT NOT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionnaire`.`user_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire`.`user_image` ;

CREATE TABLE IF NOT EXISTS `questionnaire`.`user_image` (
  `user_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  `method` INT NULL,
  PRIMARY KEY (`image_id`, `user_id`),
  CONSTRAINT `fk_user_image_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `questionnaire`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_image_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `questionnaire`.`image` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
